//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAP.Seguros.Infrastructure.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientesPolizas
    {
        public System.Guid Id { get; set; }
        public System.Guid Cliente { get; set; }
        public System.Guid Poliza { get; set; }
        public System.DateTime InicioVigencia { get; set; }
        public decimal Precio { get; set; }
        public decimal ValorAsegurado { get; set; }
        public bool Activa { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Polizas Polizas { get; set; }
    }
}
