//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAP.Seguros.Infrastructure.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CubrimientosPoliza
    {
        public int Id { get; set; }
        public System.Guid Poliza { get; set; }
        public short Cubrimiento { get; set; }
    
        public virtual Cubrimientos Cubrimientos { get; set; }
        public virtual Polizas Polizas { get; set; }
    }
}
