//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAP.Seguros.Infrastructure.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Polizas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Polizas()
        {
            this.CubrimientosPoliza = new HashSet<CubrimientosPoliza>();
            this.ClientesPolizas = new HashSet<ClientesPolizas>();
        }
    
        public System.Guid Id { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public byte PeriodoCobertura { get; set; }
        public decimal PorcentajeCubrimiento { get; set; }
        public byte Riesgo { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.Guid UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<System.Guid> UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaBorrado { get; set; }
        public Nullable<System.Guid> UsuarioBorrado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CubrimientosPoliza> CubrimientosPoliza { get; set; }
        public virtual NivelesRiesgo NivelesRiesgo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientesPolizas> ClientesPolizas { get; set; }
    }
}
