//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAP.Seguros.Infrastructure.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SegurosGAPEntities : DbContext
    {
        public SegurosGAPEntities()
            : base("name=SegurosGAPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<Cubrimientos> Cubrimientos { get; set; }
        public virtual DbSet<CubrimientosPoliza> CubrimientosPoliza { get; set; }
        public virtual DbSet<NivelesRiesgo> NivelesRiesgo { get; set; }
        public virtual DbSet<Polizas> Polizas { get; set; }
        public virtual DbSet<TiposCliente> TiposCliente { get; set; }
        public virtual DbSet<ClientesPolizas> ClientesPolizas { get; set; }
    }
}
